apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - port: 80          # cổng mà service expose trong cluster
      targetPort: 80    # ⚠️ trỏ đến containerPort trong pod
      nodePort: 30080   # cổng để truy cập từ bên ngoài node
